# Generated by Django 3.2 on 2023-04-05 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=128)),
                ('is_available', models.BooleanField(default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_persons', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('VAL', 'Проверяется'), ('CNF', 'Подтверждена'), ('CAN', 'Отменена'), ('FIN', 'Завершена')], default='NEW', max_length=3)),
                ('comment', models.CharField(blank=True, max_length=128)),
                ('client_name', models.CharField(max_length=64)),
                ('client_phone', models.CharField(max_length=12)),
                ('client_email', models.CharField(max_length=32, validators=[django.core.validators.EmailValidator])),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hall')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
            ],
        ),
    ]
