# Generated by Django 3.2 on 2023-04-08 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230407_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hall',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.hall'),
        ),
        migrations.AlterField(
            model_name='application',
            name='number_persons',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='table',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
        ),
    ]
