# Generated by Django 3.2 on 2023-04-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230408_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='hall',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.hall'),
        ),
    ]
