# Generated by Django 3.2 on 2023-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20230417_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='occupied',
            field=models.TextField(default=[]),
        ),
    ]
