# Generated by Django 3.2 on 2023-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_table_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('VAL', 'Проверяется'), ('CNF', 'Подтверждена'), ('CAN', 'Отменена'), ('FIN', 'Завершена')], max_length=3),
        ),
    ]
