# Generated by Django 3.2 on 2023-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_phone',
            field=models.CharField(max_length=17),
        ),
    ]
