# Generated by Django 3.2 on 2023-07-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_application_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
    ]
