# Generated by Django 3.2 on 2023-08-07 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to=menu.models.get_image_path)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_discount', models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount_rub', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('increment', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('increment_rub', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sticker', models.CharField(choices=[('NEW', 'Новинка'), ('SAL', 'Скидка'), ('TOP', 'Топ продаж'), ('ETY', 'Без отметки')], default='NEW', max_length=3)),
                ('is_in_POS', models.BooleanField(default=True)),
                ('is_in_delivery', models.BooleanField(default=False)),
                ('is_in_stop_list', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('position', models.CharField(choices=[('DIR', 'Директор'), ('ADM', 'Администратор'), ('MNR', 'Менеджер'), ('CAS', 'Кассир'), ('CUR', 'Курьер')], default='CAS', max_length=3)),
                ('contract', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('time_out', models.DateTimeField(blank=True)),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_take_away', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CCK', 'Готовится'), ('ASM', 'На сборке'), ('DEL', 'Передан в доставку'), ('FIN', 'Закрыт')], default='NEW', max_length=3)),
                ('dish', models.ManyToManyField(related_name='order', through='menu.DishOrder', to='menu.Dish')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.staff')),
            ],
        ),
        migrations.AddField(
            model_name='dishorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.order'),
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_section',
            field=models.ManyToManyField(related_name='dish', to='menu.MenuSection'),
        ),
        migrations.AddField(
            model_name='dish',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.store'),
        ),
    ]
