# Generated by Django 3.2 on 2023-05-22 11:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('stop_list', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('position', models.CharField(choices=[('DIR', 'Директор'), ('ADM', 'Администратор'), ('MNR', 'Менеджер'), ('CAS', 'Кассир'), ('CUR', 'Курьер')], default='CAS', max_length=3)),
                ('contract', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('take_away', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('dish', models.ManyToManyField(related_name='order', through='menu.DishOrder', to='menu.Dish')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menusection')),
            ],
        ),
        migrations.AddField(
            model_name='dishorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.order'),
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menusection'),
        ),
    ]
