# Generated by Django 3.2 on 2023-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
