# Generated by Django 3.2 on 2023-06-30 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='weight',
        ),
        migrations.AddField(
            model_name='dish',
            name='cost',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_in_POS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_in_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='margin',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='dish',
            name='sticker',
            field=models.CharField(choices=[('NEW', 'New'), ('SAL', 'Sale'), ('TOP', 'Top'), ('ETY', 'Без отметки')], default='NEW', max_length=3),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.staff'),
        ),
    ]
