# Generated by Django 3.2 on 2023-06-30 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20230630_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price_discount',
            field=models.FloatField(default=0.0, editable=False, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='margin',
            field=models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
