# Generated by Django 3.2 on 2023-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20230714_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='menu_section',
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_section',
            field=models.ManyToManyField(related_name='dish', to='menu.MenuSection'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sticker',
            field=models.CharField(choices=[('NEW', 'Новинка'), ('SAL', 'Скидка'), ('TOP', 'Топ продаж'), ('ETY', 'Без отметки')], default='NEW', max_length=3),
        ),
    ]
