# Generated by Django 3.2 on 2023-07-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20230718_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='margin',
        ),
    ]
